// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: product/prodcut.proto

package product

import (
	category "github.com/jihadable/learn-grpc-proto/category"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Category      *category.Category     `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_product_prodcut_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_product_prodcut_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_product_prodcut_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetCategory() *category.Category {
	if x != nil {
		return x.Category
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_product_prodcut_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_product_prodcut_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_product_prodcut_proto_rawDescGZIP(), []int{1}
}

type Products struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Product             `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Products) Reset() {
	*x = Products{}
	mi := &file_product_prodcut_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Products) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Products) ProtoMessage() {}

func (x *Products) ProtoReflect() protoreflect.Message {
	mi := &file_product_prodcut_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Products.ProtoReflect.Descriptor instead.
func (*Products) Descriptor() ([]byte, []int) {
	return file_product_prodcut_proto_rawDescGZIP(), []int{2}
}

func (x *Products) GetData() []*Product {
	if x != nil {
		return x.Data
	}
	return nil
}

type Id struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Id) Reset() {
	*x = Id{}
	mi := &file_product_prodcut_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Id) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Id) ProtoMessage() {}

func (x *Id) ProtoReflect() protoreflect.Message {
	mi := &file_product_prodcut_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Id.ProtoReflect.Descriptor instead.
func (*Id) Descriptor() ([]byte, []int) {
	return file_product_prodcut_proto_rawDescGZIP(), []int{3}
}

func (x *Id) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_product_prodcut_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_product_prodcut_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_product_prodcut_proto_rawDescGZIP(), []int{4}
}

func (x *Status) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_product_prodcut_proto protoreflect.FileDescriptor

const file_product_prodcut_proto_rawDesc = "" +
	"\n" +
	"\x15product/prodcut.proto\x12\aproduct\x1a\x17category/category.proto\"\x95\x01\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12.\n" +
	"\bcategory\x18\x05 \x01(\v2\x12.category.CategoryR\bcategory\"\a\n" +
	"\x05Empty\"0\n" +
	"\bProducts\x12$\n" +
	"\x04data\x18\x01 \x03(\v2\x10.product.ProductR\x04data\"\x14\n" +
	"\x02Id\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\" \n" +
	"\x06Status\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status2\x8d\x02\n" +
	"\x0eProductService\x125\n" +
	"\rCreateProduct\x12\x10.product.Product\x1a\x10.product.Product\"\x00\x122\n" +
	"\vGetProducts\x12\x0e.product.Empty\x1a\x11.product.Products\"\x00\x12-\n" +
	"\n" +
	"GetProduct\x12\v.product.Id\x1a\x10.product.Product\"\x00\x120\n" +
	"\rUpdateProduct\x12\v.product.Id\x1a\x10.product.Product\"\x00\x12/\n" +
	"\rDeleteProduct\x12\v.product.Id\x1a\x0f.product.Status\"\x00B/Z-github.com/jihadable/learn-grpc-proto/productb\x06proto3"

var (
	file_product_prodcut_proto_rawDescOnce sync.Once
	file_product_prodcut_proto_rawDescData []byte
)

func file_product_prodcut_proto_rawDescGZIP() []byte {
	file_product_prodcut_proto_rawDescOnce.Do(func() {
		file_product_prodcut_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_prodcut_proto_rawDesc), len(file_product_prodcut_proto_rawDesc)))
	})
	return file_product_prodcut_proto_rawDescData
}

var file_product_prodcut_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_product_prodcut_proto_goTypes = []any{
	(*Product)(nil),           // 0: product.Product
	(*Empty)(nil),             // 1: product.Empty
	(*Products)(nil),          // 2: product.Products
	(*Id)(nil),                // 3: product.Id
	(*Status)(nil),            // 4: product.Status
	(*category.Category)(nil), // 5: category.Category
}
var file_product_prodcut_proto_depIdxs = []int32{
	5, // 0: product.Product.category:type_name -> category.Category
	0, // 1: product.Products.data:type_name -> product.Product
	0, // 2: product.ProductService.CreateProduct:input_type -> product.Product
	1, // 3: product.ProductService.GetProducts:input_type -> product.Empty
	3, // 4: product.ProductService.GetProduct:input_type -> product.Id
	3, // 5: product.ProductService.UpdateProduct:input_type -> product.Id
	3, // 6: product.ProductService.DeleteProduct:input_type -> product.Id
	0, // 7: product.ProductService.CreateProduct:output_type -> product.Product
	2, // 8: product.ProductService.GetProducts:output_type -> product.Products
	0, // 9: product.ProductService.GetProduct:output_type -> product.Product
	0, // 10: product.ProductService.UpdateProduct:output_type -> product.Product
	4, // 11: product.ProductService.DeleteProduct:output_type -> product.Status
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_product_prodcut_proto_init() }
func file_product_prodcut_proto_init() {
	if File_product_prodcut_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_prodcut_proto_rawDesc), len(file_product_prodcut_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_prodcut_proto_goTypes,
		DependencyIndexes: file_product_prodcut_proto_depIdxs,
		MessageInfos:      file_product_prodcut_proto_msgTypes,
	}.Build()
	File_product_prodcut_proto = out.File
	file_product_prodcut_proto_goTypes = nil
	file_product_prodcut_proto_depIdxs = nil
}
